version: '3'
services:
  db_test: # Database implementation, in this case MySQL
    image: mysql:5.7
    container_name: seek-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    stop_grace_period: 1m30s
    env_file:
      - docker/db.env
    volumes:
      - seek-mysql-db-test:/var/lib/mysql

  seek_test: # The SEEK application
    build: .

    # image: fairdom/seek:master

    container_name: seek
    command: docker/entrypoint.sh
    restart: always
    environment:
      RAILS_ENV: production
      SOLR_PORT: 8983
      NO_ENTRYPOINT_WORKERS: 1
    env_file:
      - docker/db.env
    volumes:
      - seek-filestore-test:/seek/filestore
      - seek-cache-test:/seek/tmp/cache
    ports:
      - "3001:3001"
    depends_on:
      - db_test
      - solr_test
    links:
      - db_test
      - solr_test

  seek_workers_test: # The SEEK delayed job workers
      #build: .

      image: fairdom/seek:master
      container_name: seek-workers
      command: docker/start_workers.sh
      restart: always
      environment:
        RAILS_ENV: production
        SOLR_PORT: 8983
      env_file:
        - docker/db.env
      volumes:
        - seek-filestore-test:/seek/filestore
        - seek-cache-test:/seek/tmp/cache
      depends_on:
        - db_test
        - solr_test
      links:
        - db_test
        - solr_test

  solr_test:
    image: fairdom/seek-solr
    container_name: seek-solr
    restart: always
    environment:
      SOLR_JAVA_MEM: -Xms512m -Xmx1024m
    volumes:
      - seek-solr-data-test:/opt/solr/server/solr/seek/data


volumes:
  seek-filestore-test:
    external: true
  seek-mysql-db-test:
    external: true
  seek-solr-data-test:
    external: true
  seek-cache-test:
    external: true
