Plant_ArrayExpress:
    name: Plant-ArrayExpress
    group:
        plant
    source_type:
        study
    attributes:
        - attribute:
            title: Organism*
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Developmental stage*
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Age*
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Age Measurement Unit*
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Genotype*
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Cultivar*
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Organism part*
            short_name: ""
            description: ""
            IRI: ""

PlantPhenotype_MIAPPE:
    name: PlantPhenotype-MIAPPE
    group:
        plant
    source_type:
        study
    attributes:
        - attribute:
            title: Biological material ID*
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Organism*
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Genus
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Species
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Infraspecific name
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Biological material latitude
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Biological material longitude
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Biological material altitude
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Biological material coordinates uncertainty
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Biological material preprocessing
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Material source ID (Holding institute/stock centre, accession)
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Material source DOI
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Material source latitude
            short_name: ""
            description: ""
            IRI: ""

        - attribute:
            title: Material source longitude
            short_name: ""
            description: ""
            IRI: ""

        - attribute:
            title: Material source altitude
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Material source coordinates uncertainty
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Material source description
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Block ID
            short_name: ""
            description: ""
            IRI: ""

        - attribute:
            title: Sub-block ID
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Plot ID
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Sub-plot ID
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Pot ID
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Plant ID
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Block ID Spatial distribution
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Sub-block ID Spatial distribution
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Plot ID Spatial distribution
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Sub-plot ID Spatial distribution
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Pot ID Spatial distribution
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Plant ID Spatial distribution
            short_name: ""
            description: ""
            IRI: ""

Nucleic_acid_library_construction_ArrayExpress:
    name: Nucleic-acid-library-construction-ArrayExpress
    group:
        nucleic_acids
    source_type:
        assay
    attributes:
        - attribute:
            title: Library layout*
            short_name: "LibLayout"
            description: ""
            IRI: ""
        - attribute:
            title: Library source*
            short_name: "LibSource"
            description: ""
            IRI: ""
        - attribute:
            title: Library strategy*
            short_name: "LibStrategy"
            description: ""
            IRI: ""
        - attribute:
            title: Library selection*
            short_name: "LibSelection"
            description: ""
            IRI: ""
        - attribute:
            title: Library strand
            short_name: "LibStrand"
            description: ""
            IRI: ""
        - attribute:
            title: Plant ID
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Orientation
            short_name: ""
            description: ""
            IRI: ""
        - attribute:
            title: Size range (bp)
            short_name: "SizeRange (bp)"
            description: ""
            IRI: ""
        - attribute:
            title: Molarity
            short_name: "LibMol"
            description: ""
            IRI: ""
        - attribute:
            title: Barcode p5
            short_name: "p5"
            description: ""
            IRI: ""
        - attribute:
            title: Barcode p7
            short_name: "p7"
            description: ""
            IRI: "" 

Sample_collection_MIAPPE:
    name: Sample-collection-MIAPPE
    group:
        experimental_conditions
    source_type:
        assay
    attributes:
        - attribute:
            title: Sample ID*
            short_name: "SampleID"
            description: "Unique identifier for the sample."
            IRI: ""
        - attribute:
            title: Plant structure development stage
            short_name: "DevStage"
            description: "The stage in the life of a plant structure during which the sample was taken, in the form of an accession number to a suitable controlled vocabulary (Plant Ontology, BBCH scale)"
            IRI: ""
        - attribute:
            title: Plant anatomical entity*
            short_name: "PlantPart"
            description: "A description of  the plant part (e.g. leaf) or the plant product (e.g. resin) from which the sample was taken, in the form of an accession number to a suitable controlled vocabulary (Plant Ontology)."
            IRI: ""
        - attribute:
            title: Sample description
            short_name: "Sample"
            description: "Any information not captured by the other sample fields, including quantification, sample treatments and processing."
            IRI: ""
        - attribute:
            title: Collection date*
            short_name: "CollectionDate"
            description: "The date and time when the sample was collected / harvested"
            IRI: ""
        - attribute:
            title: External ID
            short_name: "ExtarnalID"
            description: "An identifier for the sample in a persistent repository, comprising the name of the repository and the accession number of the observation unit therein. Submission to the EBI Biosamples repository is recommended. URI are recommended when possible."
            IRI: ""

Nucleic_acid_library_construction_ILVO:
    name: Nucleic-acid-library-construction-ILVO*
    group:
        nucleic_acids
    source_type:
        assay
    attributes:
        - attribute:
            title: Library layout*
            short_name: "LibLayout"
            description: "ENA ontology(single, paired, loci, targeted)"
            IRI: ""
        - attribute:
            title: Library source*
            short_name: "LibSource"
            description: "ENA ontology(Genomic, Transcriptomics, Viral RNA)"
            IRI: ""
        - attribute:
            title: Library strategy*
            short_name: "LibStrategy"
            description: "ENA ontology(RNA-seq, GBS)"
            IRI: ""
        - attribute:
            title: Library selection*
            short_name: "LibSelection"
            description: ""
            IRI: "ENA ontology(random, RT-PCR, PCR, cDNA_oligo_dT, Restriction digest)"
        - attribute:
            title: Library Restriction Enzyme
            short_name: "LibRE"
            description: ""
            IRI: ""
        - attribute:
            title: Library Kit
            short_name: "LibKit"
            description: ""
            IRI: ""
        - attribute:
            title: Library Protocol Name and Version
            short_name: "LibProtocol_v"
            description: "Name and version of the used protocol"
            IRI: ""
        - attribute:
            title: Library Primers
            short_name: "Libprimers"
            description: ""
            IRI: ""
        - attribute:
            title: Primers code
            short_name: "P_code"
            description: ""
            IRI: ""

Nucleic_acid_sequencing_ILVO*:
    name: Nucleic-acid-sequencing-ILVO*
    group:
        nucleic_acids
    source_type:
        assay
    attributes:
        - attribute:
            title: Instrument platform
            short_name: "Platform"
            description: ""
            IRI: ""
        - attribute:
            title: Instrument model
            short_name: "Model"
            description: ""
            IRI: ""
        - attribute:
            title: # Re-sequencing
            short_name: "# Re-seq"
            description: "sequential number indicating the number of times that the same sample (individual) is sequenced with the same  technology (library)"
            IRI: ""
        - attribute:
            title: Re-sequencing_code
            short_name: "# re-seq_code"
            description: "sequential number indicating the number of times that the same sample (individual) is sequenced with the same  technology (library)"
            IRI: ""
        - attribute:
            title: Run
            short_name: "run"
            description: ""
            IRI: ""
        - attribute:
            title: Flowcell_code
            short_name: "flowcell_code"
            description: ""
        - attribute:
            title: Code
            short_name: "code"
            description: ""
        - attribute:
            title: Remarks after data analysis
            short_name: "PostAnalysis_remarks"
            description: ""
            IRI: ""
        - attribute:
            title: Lane
            short_name: "lane"
            description: ""
            IRI: ""
        - attribute:
            title: Unique sample_code
            short_name: "sample_id"
            description: ""
            IRI: ""
        - attribute:
            title: Barcode i5
            short_name: "i5"
            description: ""
            IRI: ""
        - attribute:
            title: Barcode i7
            short_name: "i7"
            description: ""
            IRI: ""
        - attribute:
            title: i5_code
            short_name: "i5_code"
            description: "adaptor index  i5 code "
            IRI: ""
        - attribute:
            title: i7_code
            short_name: "i7_code"
            description: "adaptor index  i7 code "
            IRI: ""
        - attribute:
            title: md5 value PE forward
            short_name: "md5_PE_F"
            description: ""
            IRI: ""
        - attribute:
            title: md5 value PE reverse
            short_name: "md5_PE_R"
            description: ""
            IRI: ""
        - attribute:
            title: md5 value SE
            short_name: "md5_SE"
            description: ""
            IRI: ""
            